In [20]:
import urllib.request, json 
import datetime
import time as t

loaded_data = []
data=None
t_runtime = 60*60*24
t_step = 5
t_elapsed = 0
running_dict = {}
while t_elapsed < t_runtime:
    t_elapsed+=t_step
    t.sleep(t_step)
    print(t_elapsed, end='\r')
    with urllib.request.urlopen("https://s3.amazonaws.com/kcm-alerts-realtime-prod/vehiclepositions_pb.json") as url:
        data = json.load(url)
        time = datetime.datetime.now()
        bus_id = pd.Series(pd.DataFrame(data['entity'])['id']).apply(lambda x: x.split("_")[1])
        route_id = pd.DataFrame(data['entity'])['vehicle'].apply(lambda x: x['trip']['route_id'])
        direction = pd.DataFrame(data['entity'])['vehicle'].apply(lambda x: x['trip']['direction_id'])
        position =  pd.DataFrame(data['entity'])['vehicle'].apply(lambda x: shapely.Point(x['position']['latitude'], x['position']['longitude']))
        data = pd.DataFrame([pd.Series(list(route_id)), pd.Series(list(bus_id)), pd.Series(list(direction))]).T
        data = data.rename(columns={0:'rid',1:'bid',2:'dir'})
        
        
        timepoint = pd.DataFrame([position]).T
        timepoint = timepoint.rename(columns={'vehicle':'geometry'})
        data['points'] = timepoint.apply(lambda x: (time, x.geometry), axis=1)
        
        for col, row in data.iterrows():
            x = row
            if "{}_{}_{}".format(x.rid,x.bid,x.dir) not in running_dict.keys():
                running_dict["{}_{}_{}".format(x.rid,x.bid,x.dir)] = []
                running_dict["{}_{}_{}".format(x.rid,x.bid,x.dir)].append(x.points)
            else:
                running_dict["{}_{}_{}".format(x.rid,x.bid,x.dir)].append(x.points)
        #data.apply(lambda x: running_dict["{}_{}_{}".format(x.rid,x.bid,x.dir)] = [x.points] if "{}_{}_{}".format(x.rid,x.bid,x.dir) not in running_dict.keys() else running_dict["{}_{}_{}".format(x.rid,x.bid,x.dir)].append(x.points), axis=1)

timelog = pd.DataFrame([running_dict.keys(), running_dict.values()]).T
timelog['rt'] = timelog[0].apply(lambda x: x.split("_")[0])
timelog['bus'] = timelog[0].apply(lambda x: x.split("_")[1])
timelog['dir'] = timelog[0].apply(lambda x: x.split("_")[2])

In [30]:
import Object_Params as op
import importlib
importlib.reload(op)
op.load_trip_params("./..//..//..//..//..//..//media/sebastian/Slepnir/Saved_Objects/Trips/Base_XDE35_trip.txt").traffic

IndexError: list index out of range

In [23]:
timelog.to_csv('bus_time_tracking.csv')

In [24]:
timelog

,0,1,rt,bus,dir
0,100001_4364_0,"[(2025-01-27 14:30:10.253487, POINT (47.61013 ...",100001,4364,0
1,100001_4395_1,"[(2025-01-27 14:30:10.253487, POINT (47.645114...",100001,4395,1
2,100001_4341_0,"[(2025-01-27 14:30:10.253487, POINT (47.62603 ...",100001,4341,0
3,100001_4374_1,"[(2025-01-27 14:30:10.253487, POINT (47.641532...",100001,4374,1
4,100002_4329_1,"[(2025-01-27 14:30:10.253487, POINT (47.61524 ...",100002,4329,1
...,...,...,...,...,...
883,100026_7438_1,"[(2025-01-27 15:02:22.720757, POINT (47.585453...",100026,7438,1
884,100005_7002_0,"[(2025-01-27 15:02:44.701472, POINT (47.599193...",100005,7002,0
885,100133_7317_1,"[(2025-01-27 15:02:50.200999, POINT (47.615665...",100133,7317,1
886,100214_6994_0,"[(2025-01-27 15:02:50.200999, POINT (47.66227 ...",100214,6994,0
887,100249_7003_0,"[(2025-01-27 15:02:50.200999, POINT (47.623954...",100249,7003,0

In [16]:
routes = pd.DataFrame(pd.Series(saved_routes))
# Make the column 'path'
routes.columns = ['path']

In [17]:
routes

                                                  path
0    ./..//..//..//..//..//..//media/sebastian/Slep...
1    ./..//..//..//..//..//..//media/sebastian/Slep...
2    ./..//..//..//..//..//..//media/sebastian/Slep...
3    ./..//..//..//..//..//..//media/sebastian/Slep...
4    ./..//..//..//..//..//..//media/sebastian/Slep...
..                                                 ...
521  ./..//..//..//..//..//..//media/sebastian/Slep...
522  ./..//..//..//..//..//..//media/sebastian/Slep...
523  ./..//..//..//..//..//..//media/sebastian/Slep...
524  ./..//..//..//..//..//..//media/sebastian/Slep...
525  ./..//..//..//..//..//..//media/sebastian/Slep...

[526 rows x 1 columns]